# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

########## Stage 1: Large image to build toolchains and emulator ##########
FROM ubuntu:22.04 AS toolchain

ARG PYTHON_VERSION=3.8.0
ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive

ENV TZ=Etc/UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV CC="ccache gcc"
ENV CXX="ccache g++"
ENV CCACHE_DIR=/ccache
ENV DEEPLOY_INSTALL_DIR=/app/install

# Change the working directory
WORKDIR /app/build

# Install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git-lfs \
    build-essential \
    ccache \
    ninja-build \
    pkg-config \
    ibglib2.0-dev \
    libpixman-1-dev \
    python3 \
    python3-dev \
    python-is-python3 \
    python3.10-venv \
    python3.10-distutils \
    curl \
    protobuf-compiler \
    libftdi-dev \
    libftdi1 \
    doxygen \
    libsdl2-dev \
    scons \
    gtkwave \
    libsndfile1-dev \
    rsync \
    autoconf \
    automake \
    texinfo \
    libtool \
    libsdl2-ttf-dev \
    gcc \
    wget \
    clang-format

# Install CMake
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    wget https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-linux-x86_64.sh && \
    chmod +x cmake-3.31.1-linux-x86_64.sh && \
    ./cmake-3.31.1-linux-x86_64.sh --prefix=/usr --skip-license; \
elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    wget https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-linux-aarch64.sh && \
    chmod +x ./cmake-3.31.1-linux-aarch64.sh && \
    ./cmake-3.31.1-linux-aarch64.sh --prefix=/usr --skip-license; \
fi

# Install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py && \
    rm get-pip.py

# Install meson
RUN pip install meson

COPY toolchain/ toolchain/
COPY Makefile ./

# Compile minimalloc
RUN --mount=type=cache,target=/ccache \
    ccache -z && make minimalloc && ccache -s

# Compile toolchains
RUN --mount=type=cache,target=/ccache \
    ccache -z && make llvm && make llvm-compiler-rt-riscv && \
    make llvm-compiler-rt-arm && make picolibc-arm && \
    make picolibc-riscv && ccache -s

# Remove unecessary files
WORKDIR /app
RUN rm -rf build
