# SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV LLVM_INSTALL_DIR="nope"

RUN apt-get update && apt-get install -y \
    software-properties-common \
    && add-apt-repository -y ppa:amd-team/xrt \
    && apt-get update && apt-get install -y \
    cmake \
    ninja-build \
    g++ \
    git \
    git-lfs \
    python3 \
    python3-pip \
    python-is-python3 \
    uuid-dev \
    wget \
    curl \
    ccache \
    libxrt2 \
    libxrt-npu2 \
    libxrt-dev \
    libxrt-utils \
    libxrt-utils-npu \
    && rm -rf /var/lib/apt/lists/*

ENV XILINX_XRT=/opt/xilinx/xrt
ENV PATH=${XILINX_XRT}/bin:${PATH}
ENV LD_LIBRARY_PATH=${XILINX_XRT}/lib


WORKDIR /app
COPY pyproject.toml ./
RUN pip install toml-to-requirements && \
    toml-to-req --toml-file pyproject.toml && \
    pip install -r requirements.txt && \
    rm -f requirements.txt pyproject.toml

RUN pip install \
    --extra-index-url https://github.com/Xilinx/mlir-aie/releases/expanded_assets/v1.2.1 \
    --extra-index-url https://github.com/Xilinx/llvm-aie/releases/expanded_assets/nightly \
    "mlir_aie==v1.2.1" \
    llvm-aie

ENV MLIR_AIE_PYTHON=/usr/bin/python3

WORKDIR /app/Deeploy
