#!/usr/bin/env bash
# Pareto sweep across models generated by Onnx4Deeploy topk-forward.
set -u
cd "$(dirname "$0")/.."

LOG_DIR="$(pwd)/scripts/logs/pareto_topk_sweep"
CSV_OUT="$(pwd)/scripts/logs/benchmark/pareto_topk_sweep.csv"
mkdir -p "$LOG_DIR" "$(dirname "$CSV_OUT")"
if [ ! -f "$CSV_OUT" ]; then
  echo "model,variant,l2_peak,fwd_bwd_cycles,opt_cycles" > "$CSV_OUT"
fi

NOGCP_FLAGS="--n-steps 1 --l1 128000 --l2 2000000 --defaultMemLevel L2 --tolerance 0.09"
COSTK_FLAGS="--n-steps 10 --l1 128000 --l2 1500000 --defaultMemLevel L2 --tolerance 0.09"
RESNET_COSTK_FLAGS="--n-steps 10 --l1 128000 --l2 2000000 --defaultMemLevel L2 --tolerance 0.09"
MOBILENET_NOGCP_FLAGS="--n-steps 1 --l1 128000 --l2 2000000 --defaultMemLevel L3 --tolerance 0.09"
MOBILENET_COSTK_FLAGS="--n-steps 10 --l1 128000 --l2 2000000 --defaultMemLevel L3 --tolerance 0.09"

MODELS=(
  "DSCNN|dscnn|1,2,3,5,8,11,12,18|"
  "CCT_2|cct_2|1,2,4,9,17,19|"
  "CCT_3|cct_3|1,2,4,8,15,21|"
  "ResNet8|resnet8|1,2,4,8,11,13,16,20|RESNET"
  "MobileNetV1|mobilenetv1|1,4,8,16,24,32,40,48|MOBILENET"
)

FILTER=${1:-}

run_one () {
  local model="$1"
  local variant="$2"
  local test_dir="$3"
  local opt_dir="$4"
  local flags="$5"
  local log="$LOG_DIR/${model,,}_${variant,,}.log"

  echo ">>> $model $variant"
  if [ ! -d "$test_dir" ]; then
    echo "    SKIP (no test dir)"
    echo "$model,$variant,MISSING,MISSING,MISSING" >> "$CSV_OUT"
    return
  fi

  python deeployTrainingRunner_tiled_siracusa.py \
    -t "$test_dir" \
    --optimizer-dir "$opt_dir" \
    --n-accum 4 -vvv --plotMemAlloc \
    $flags > "$log" 2>&1
  local rc=$?
  if [ $rc -ne 0 ]; then
    echo "    FAILED (log $log)"
    echo "$model,$variant,FAIL,FAIL,FAIL" >> "$CSV_OUT"
    return
  fi

  local bench=$(grep -E "^BENCH " "$log" | tail -1 || true)
  local tc oc
  if [ -n "$bench" ]; then
    tc=$(echo "$bench" | sed -E 's/.*train_cycles=([0-9]+).*/\1/')
    oc=$(echo "$bench" | sed -E 's/.*opt_cycles=([0-9]+).*/\1/')
  else
    tc=$(awk '/\[BENCH\] --- Training/{s=1} /\[BENCH\][[:space:]]+avg/{if(s){for(i=1;i<=NF;i++)if($i=="=")print $(i+1);exit}}' "$log")
    oc=$(awk '/\[BENCH\] --- Optimizer/{s=1} /\[BENCH\][[:space:]]+avg/{if(s){for(i=1;i<=NF;i++)if($i=="=")print $(i+1);exit}}' "$log")
  fi
  local peak=$(grep -oP 'L2\s+MEMORYARENA_len\s*=\s*\K[0-9]+' "$log" | tail -1 || true)
  [ -z "$peak" ] && peak=$(grep -oP 'L2[[:space:]]+[0-9,]+[[:space:]]+\K[0-9,]+' "$log" | head -1 | tr -d ',' || true)

  echo "    L2=${peak:-?}  train=${tc:-?}  opt=${oc:-?}"
  echo "$model,$variant,${peak:-?},${tc:-?},${oc:-?}" >> "$CSV_OUT"
}

rm -rf TEST_SIRACUSA/build_master

for spec in "${MODELS[@]}"; do
  IFS='|' read -r model lower klist override <<<"$spec"
  if [ -n "$FILTER" ] && [ "$FILTER" != "${lower}" ] && [ "$FILTER" != "${model,,}" ]; then continue; fi

  case "$override" in
    RESNET)    NOGCP="$NOGCP_FLAGS";           COSTK="$RESNET_COSTK_FLAGS" ;;
    MOBILENET) NOGCP="$MOBILENET_NOGCP_FLAGS"; COSTK="$MOBILENET_COSTK_FLAGS" ;;
    *)         NOGCP="$NOGCP_FLAGS";           COSTK="$COSTK_FLAGS" ;;
  esac

  echo ""
  echo "================================================================"
  echo " $model"
  echo "================================================================"

  run_one "$model" "nogcp" \
    "./Tests/Models/Training/${model}_UNI_NOGCP/${lower}_train/" \
    "./Tests/Models/Training/${model}_UNI_NOGCP/${lower}_optimizer/" \
    "$NOGCP"

  IFS=',' read -ra ks <<<"$klist"
  for K in "${ks[@]}"; do
    run_one "$model" "k${K}" \
      "./Tests/Models/Training/${model}_UNI_K${K}/${lower}_train/" \
      "./Tests/Models/Training/${model}_UNI_K${K}/${lower}_optimizer/" \
      "$COSTK"
  done
done

echo ""
echo "DONE. CSV: $CSV_OUT"
