// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
//
// SPDX-License-Identifier: Apache-2.0

// XRT C++ testbench for the XDNA2 (AIE2p) platform.
// Loads network.xclbin produced by aiecc.py, runs the MLIR_AIE kernel,
// reads back outputs and compares against golden reference values.
// Output format: "Errors: X out of Y" (required by output_parser.py).

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_hw_context.h"
#include "xrt/xrt_kernel.h"

// Generated by Deeploy's generateNetwork_xdna2.py:
//   testinputs.h  – uint16_t arrays of BF16 bit patterns + N_ELEMENTS_INPUT{i} defines
//   testoutputs.h – uint16_t arrays of BF16 bit patterns + N_ELEMENTS_OUTPUT{i} defines
#include "testinputs.h"
#include "testoutputs.h"

// ---------------------------------------------------------------------------
// BF16 helpers
// ---------------------------------------------------------------------------
static float bf16_to_float(uint16_t bf16)
{
    uint32_t f32_bits = static_cast<uint32_t>(bf16) << 16;
    float f;
    std::memcpy(&f, &f32_bits, sizeof(f));
    return f;
}

static bool bf16_nearly_equal(uint16_t a, uint16_t b,
                              float rtol = 0.0f, float atol = 0.0f)
{
    // Default: allow 1 BF16 ULP difference to account for hardware rounding.
    // A BF16 ULP at a given magnitude is the gap between adjacent BF16 values.
    float fa = bf16_to_float(a);
    float fb = bf16_to_float(b);
    float diff = std::fabs(fa - fb);

    // Compute 1 ULP for the reference value's magnitude
    uint16_t ref_exp = (b >> 7) & 0xFF;  // BF16 exponent (8 bits)
    float ulp;
    if (ref_exp == 0)
        ulp = std::ldexp(1.0f, -133);  // subnormal ULP
    else
        ulp = std::ldexp(1.0f, static_cast<int>(ref_exp) - 127 - 7);  // 7 mantissa bits

    float tol = std::fmax(atol + rtol * std::fabs(fb), ulp);
    return diff <= tol;
}

// ---------------------------------------------------------------------------
// Read the NPU instruction binary produced by aiecc.py
// ---------------------------------------------------------------------------
static std::vector<uint32_t> read_instr_binary(const std::string &path)
{
    std::ifstream file(path, std::ios::binary);
    if (!file.is_open()) {
        throw std::runtime_error("Cannot open instruction file: " + path);
    }
    file.seekg(0, std::ios::end);
    size_t byte_size = file.tellg();
    file.seekg(0, std::ios::beg);

    std::vector<uint32_t> instr(byte_size / sizeof(uint32_t));
    file.read(reinterpret_cast<char *>(instr.data()), byte_size);
    return instr;
}

int main(int argc, char **argv)
{
    // Paths to the compiled artefacts (relative to the binary's working dir)
    std::string xclbin_path = "/scratch/jungvi/Deeploy/DeeployTest/TEST_XDNA2/build_master/bin/network.xclbin";
    std::string instr_path  = "/scratch/jungvi/Deeploy/DeeployTest/TEST_XDNA2/build_master/bin/npu_insts.bin";

    bool verbose = false;
    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-v" || arg == "--verbose" || arg == "-vv") {
            verbose = true;
        }
    }
    if (argc >= 2 && argv[1][0] != '-') xclbin_path = argv[1];
    if (argc >= 3 && argv[2][0] != '-') instr_path  = argv[2];

    // -----------------------------------------------------------------------
    // 1. Open XRT device, register xclbin, create hw_context
    //    (matches mlir-aie test_utils::init_xrt_load_kernel pattern)
    // -----------------------------------------------------------------------
    auto device = xrt::device(0);
    auto xclbin = xrt::xclbin(xclbin_path);
    device.register_xclbin(xclbin);
    xrt::hw_context context(device, xclbin.get_uuid());
    auto kernel = xrt::kernel(context, "MLIR_AIE");

    // -----------------------------------------------------------------------
    // 2. Read NPU instruction binary
    // -----------------------------------------------------------------------
    std::vector<uint32_t> instr_v = read_instr_binary(instr_path);
    size_t n_instr = instr_v.size();

    // -----------------------------------------------------------------------
    // 3. Derive element counts from the testinputs/testoutputs header defines.
    //    N_ELEMENTS_INPUT0, N_ELEMENTS_INPUT1, N_ELEMENTS_OUTPUT0 are set
    //    by generateNetwork_xdna2.py.
    // -----------------------------------------------------------------------
    static_assert(N_ELEMENTS_INPUT0 == N_ELEMENTS_INPUT1,
                  "Input 0 and input 1 must have the same number of elements");
    static_assert(N_ELEMENTS_INPUT0 == N_ELEMENTS_OUTPUT0,
                  "Inputs and output must have the same number of elements");

    const size_t n_elem    = N_ELEMENTS_OUTPUT0;
    const size_t elem_size = sizeof(uint16_t);   // BF16 = 2 bytes
    const size_t buf_bytes = n_elem * elem_size;

    // -----------------------------------------------------------------------
    // 4. Allocate XRT buffer objects
    //    Kernel args: (0:opcode, 1:instr_bo, 2:instr_len, 3:in0, 4:in1, 5:out)
    // -----------------------------------------------------------------------
    auto bo_instr = xrt::bo(device, n_instr * sizeof(uint32_t),
                            XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));
    auto bo_in0   = xrt::bo(device, buf_bytes, XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3));
    auto bo_in1   = xrt::bo(device, buf_bytes, XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(4));
    auto bo_out   = xrt::bo(device, buf_bytes, XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(5));

    // -----------------------------------------------------------------------
    // 5. Copy data into device buffers
    // -----------------------------------------------------------------------
    std::memcpy(bo_instr.map<uint32_t *>(), instr_v.data(), n_instr * sizeof(uint32_t));
    std::memcpy(bo_in0.map<void *>(), testInputVector0, buf_bytes);
    std::memcpy(bo_in1.map<void *>(), testInputVector1, buf_bytes);

    bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);
    bo_in0.sync(XCL_BO_SYNC_BO_TO_DEVICE);
    bo_in1.sync(XCL_BO_SYNC_BO_TO_DEVICE);

    // -----------------------------------------------------------------------
    // 6. Launch kernel and wait for completion
    //    opcode 3 = execute NPU instruction stream
    // -----------------------------------------------------------------------
    unsigned int opcode = 3;
    auto run = kernel(opcode, bo_instr, static_cast<uint32_t>(n_instr),
                      bo_in0, bo_in1, bo_out);
    run.wait();

    // -----------------------------------------------------------------------
    // 7. Sync output back and compare against golden reference
    // -----------------------------------------------------------------------
    bo_out.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

    const uint16_t *hw_out     = bo_out.map<const uint16_t *>();
    const uint16_t *golden_out = testOutputVector0;

    int errors = 0;
    for (size_t i = 0; i < n_elem; ++i) {
        bool match = bf16_nearly_equal(hw_out[i], golden_out[i]);
        if (!match) {
            ++errors;
            if (errors <= 10) {
                std::cerr << "  Mismatch at index " << i
                          << ": hw=" << bf16_to_float(hw_out[i])
                          << " (0x" << std::hex << hw_out[i] << std::dec << ")"
                          << "  ref=" << bf16_to_float(golden_out[i])
                          << " (0x" << std::hex << golden_out[i] << std::dec << ")"
                          << "  diff=" << std::fabs(bf16_to_float(hw_out[i]) - bf16_to_float(golden_out[i]))
                          << "\n";
            }
        }
        if (verbose) {
            float hw_f  = bf16_to_float(hw_out[i]);
            float ref_f = bf16_to_float(golden_out[i]);
            std::cout << "[" << i << "] hw=" << hw_f
                      << "  ref=" << ref_f
                      << "  diff=" << std::fabs(hw_f - ref_f)
                      << (match ? "" : "  *** MISMATCH")
                      << "\n";
        }
    }

    // Output format required by testUtils/core/output_parser.py
    std::cout << "Errors: " << errors << " out of " << n_elem << "\n";

    return (errors == 0) ? 0 : 1;
}
