# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

"""XDNA2 network generation script.

JUNGVI: TODO: Move this script to ONNX4Deeploy

Replaces the generic ``generateNetwork.py`` for the XDNA2 platform.
Instead of emitting C code it:

1. Loads the ONNX model and npz test-data.
2. Prepares the XDNA2Deployer (type checking + graph binding).
3. Emits ``testinputs.h`` and ``testoutputs.h`` with raw BF16 uint16_t arrays.
4. Calls ``deployer.generateMLIR()`` and writes ``network.mlir``.
"""

import os
import struct

import numpy as np
import onnx
import onnx_graphsurgeon as gs

from testUtils.platformMapping import mapDeployer, mapPlatform
from testUtils.testRunner import TestGeneratorArgumentParser
from testUtils.typeMapping import inferTypeAndOffset

from Deeploy.AbstractDataTypes import PointerClass
from Deeploy.CommonExtensions.DataTypes import bfloat16_t
from Deeploy.DeeployTypes import _NoVerbosity
from Deeploy.Logging import DEFAULT_LOGGER as log


def _float32_to_bf16_uint16(arr: np.ndarray) -> np.ndarray:
    """Convert a float32 numpy array to an array of BF16 bit patterns (uint16_t).

    Uses round-to-nearest-even (the standard IEEE 754 rounding mode).
    """
    f32 = arr.astype(np.float32)
    raw = f32.view(np.uint32)
    # Standard round-to-nearest-even: add 0x7FFF + BF16_LSB to the full word,
    # then truncate.  The 0x7FFF biases values just below the midpoint to
    # round down, while adding the BF16 LSB provides tie-breaking to even.
    bf16_lsb = (raw >> 16) & 1
    raw = raw + np.uint32(0x7FFF) + bf16_lsb
    bf16 = (raw >> 16).astype(np.uint16)
    return bf16


def _bf16_to_float32(bf16: np.ndarray) -> np.ndarray:
    """Convert an array of BF16 uint16 bit patterns back to float32."""
    f32_bits = bf16.astype(np.uint32) << 16
    return f32_bits.view(np.float32)


def _generate_xdna2_inputs_header(input_arrays: list) -> str:
    """Generate testinputs.h with raw uint16_t BF16 bit-pattern arrays."""
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(input_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testInputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_INPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testInputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _generate_xdna2_outputs_header(output_arrays: list) -> str:
    """Generate testoutputs.h with raw uint16_t BF16 bit-pattern arrays."""
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(output_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testOutputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_OUTPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testOutputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generateNetworkXDNA2(args):
    log.debug("Arguments: %s", args)

    onnx_graph = onnx.load_model(f'{args.dir}/network.onnx')
    graph = gs.import_onnx(onnx_graph)

    inputs_npz = np.load(f'{args.dir}/inputs.npz')
    outputs_npz = np.load(f'{args.dir}/outputs.npz')

    test_inputs_f32 = [inputs_npz[x] for x in inputs_npz.files]
    test_outputs_f32 = [outputs_npz[x] for x in outputs_npz.files]

    # XDNA2 is a non-signprop platform: signProp = False
    platform, signProp = mapPlatform(args.platform)

    inputTypes = {}
    inputOffsets = {}

    for index, (name, values) in enumerate(zip(inputs_npz.files, test_inputs_f32)):
        if np.prod(values.shape) == 0:
            continue
        # Force bfloat16_t — BF16 test data stored as float32 in npz would be
        # inferred as float32_t by minimalFloatType, but the XDNA2 kernel
        # requires bfloat16_t inputs.
        inputTypes[f"input_{index}"] = PointerClass(bfloat16_t)
        inputOffsets[f"input_{index}"] = 0

    _DEEPLOYSTATEDIR = os.path.join(args.dumpdir, "deeployStates")

    deployer = mapDeployer(platform,
                           graph,
                           inputTypes,
                           deeployStateDir=_DEEPLOYSTATEDIR,
                           inputOffsets=inputOffsets)

    # Prepare the deployer (type checking + binding)
    deployer.prepare(_NoVerbosity)

    # Create output directory
    os.makedirs(args.dumpdir, exist_ok=True)

    # Write testinputs.h (raw BF16 bit patterns as uint16_t)
    testInputStr = _generate_xdna2_inputs_header(test_inputs_f32)
    with open(f'{args.dumpdir}/testinputs.h', 'w') as f:
        f.write(testInputStr)

    # Recompute golden outputs from the actual BF16 inputs the hardware will
    # see.  The original outputs.npz may have been computed in float32
    # precision, which can differ by several BF16 ULPs.
    bf16_inputs = [_float32_to_bf16_uint16(a.flatten()) for a in test_inputs_f32]
    bf16_input_f32 = [_bf16_to_float32(b) for b in bf16_inputs]
    golden_f32 = bf16_input_f32[0]
    for inp in bf16_input_f32[1:]:
        golden_f32 = golden_f32 + inp
    test_outputs_bf16 = [golden_f32.reshape(arr.shape) for arr in test_outputs_f32]

    # Write testoutputs.h (raw BF16 bit patterns as uint16_t)
    testOutputStr = _generate_xdna2_outputs_header(test_outputs_bf16)
    with open(f'{args.dumpdir}/testoutputs.h', 'w') as f:
        f.write(testOutputStr)

    # Write network.mlir
    mlir_str = deployer.generateMLIR()
    with open(f'{args.dumpdir}/network.mlir', 'w') as f:
        f.write(mlir_str)

    log.info(f"[XDNA2] Generated: testinputs.h, testoutputs.h, network.mlir -> {args.dumpdir}")


if __name__ == '__main__':
    parser = TestGeneratorArgumentParser(description="Deeploy XDNA2 Code Generation Utility.")
    args = parser.parse_args()

    if args.platform != 'XDNA2':
        parser.error(f"This script is for the XDNA2 platform. Got: {args.platform}")

    generateNetworkXDNA2(args)
