# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0
"""XDNA2 network generation script.

JUNGVI: TODO: Move this script to ONNX4Deeploy

Replaces the generic ``generateNetwork.py`` for the XDNA2 platform.
Instead of emitting C code it:

1. Loads the ONNX model and npz test-data.
2. Prepares the XDNA2Deployer (type checking + graph binding).
3. Emits ``testinputs.h`` and ``testoutputs.h`` with raw BF16 uint16_t arrays.
4. Calls ``deployer.generateMLIR()`` and writes ``network.mlir``.
"""

import os

import numpy as np
import onnx
import onnx_graphsurgeon as gs
from testUtils.platformMapping import mapDeployer
from testUtils.testRunner import TestGeneratorArgumentParser

from Deeploy.AbstractDataTypes import PointerClass
from Deeploy.CommonExtensions.DataTypes import bfloat16_t
from Deeploy.Logging import DEFAULT_LOGGER as log
from Deeploy.MemoryLevelExtension.MemoryLevels import MemoryHierarchy, MemoryLevel
from Deeploy.MemoryLevelExtension.NetworkDeployers.MemoryLevelDeployer import MemoryDeployerWrapper
from Deeploy.Targets.XDNA2.Platform import MemoryXDNA2Platform, XDNA2AIECoreEngine, XDNA2TilingMapping
from Deeploy.TilingExtension.TilerExtension import TilerDeployerWrapper


def _tilingScheduler(graph: gs.Graph):
    """Scheduler that returns List[List[gs.Node]] as required by the tiling framework."""
    return [[node] for node in graph.nodes]


def _float32_to_bf16_uint16(arr: np.ndarray) -> np.ndarray:
    """Convert a float32 numpy array to an array of BF16 bit patterns (uint16_t).

    Uses round-to-nearest-even (the standard IEEE 754 rounding mode).
    """
    f32 = arr.astype(np.float32)
    raw = f32.view(np.uint32)
    # Standard round-to-nearest-even: add 0x7FFF + BF16_LSB to the full word,
    # then truncate.  The 0x7FFF biases values just below the midpoint to
    # round down, while adding the BF16 LSB provides tie-breaking to even.
    bf16_lsb = (raw >> 16) & 1
    raw = raw + np.uint32(0x7FFF) + bf16_lsb
    bf16 = (raw >> 16).astype(np.uint16)
    return bf16


def _bf16_to_float32(bf16: np.ndarray) -> np.ndarray:
    """Convert an array of BF16 uint16 bit patterns back to float32."""
    f32_bits = bf16.astype(np.uint32) << 16
    return f32_bits.view(np.float32)


def _generate_xdna2_inputs_header(input_arrays: list) -> str:
    """Generate testinputs.h with raw uint16_t BF16 bit-pattern arrays."""
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(input_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testInputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_INPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testInputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _generate_xdna2_outputs_header(output_arrays: list) -> str:
    """Generate testoutputs.h with raw uint16_t BF16 bit-pattern arrays."""
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(output_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testOutputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_OUTPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testOutputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generateNetworkXDNA2(args):
    log.debug("Arguments: %s", args)

    onnx_graph = onnx.load_model(f'{args.dir}/network.onnx')
    graph = gs.import_onnx(onnx_graph)

    inputs_npz = np.load(f'{args.dir}/inputs.npz')
    outputs_npz = np.load(f'{args.dir}/outputs.npz')

    test_inputs_f32 = [inputs_npz[x] for x in inputs_npz.files]
    test_outputs_f32 = [outputs_npz[x] for x in outputs_npz.files]

    inputTypes = {}
    inputOffsets = {}

    for index, (name, values) in enumerate(zip(inputs_npz.files, test_inputs_f32)):
        if np.prod(values.shape) == 0:
            continue
        # Force bfloat16_t — BF16 test data stored as float32 in npz would be
        # inferred as float32_t by minimalFloatType, but the XDNA2 kernel
        # requires bfloat16_t inputs.
        inputTypes[f"input_{index}"] = PointerClass(bfloat16_t)
        inputOffsets[f"input_{index}"] = 0

    _DEEPLOYSTATEDIR = os.path.join(args.dumpdir, "deeployStates")

    # Define memory hierarchy: L1 (AIE core local) and L3 (shared)
    l1_size = int(getattr(args, 'l1', None) or 8192)  # 8KB default
    l3_size = int(getattr(args, 'l3', None) or 128 * 1024 * 1024)  # 128MB default

    log.info(f"[XDNA2] Using MemoryXDNA2Platform with L1={l1_size}, L3={l3_size}")

    l1_level = MemoryLevel("L1", neighbourNames = ["L3"], size = l1_size)
    l3_level = MemoryLevel("L3", neighbourNames = ["L1"], size = l3_size)
    memory_hierarchy = MemoryHierarchy([l1_level, l3_level])
    memory_hierarchy.setDefaultMemoryLevel("L3")  # Tensors default to L3

    # Create memory-aware platform with AIE core engine
    # defaultTargetMemoryLevel=L1 tells the tiling framework that computation
    # targets L1, so it must tile data from L3 into L1-sized chunks.
    mem_platform = MemoryXDNA2Platform(
        memoryHierarchy = memory_hierarchy,
        defaultTargetMemoryLevel = l1_level,
        engines = [XDNA2AIECoreEngine(Mapping = XDNA2TilingMapping, preferredMemoryLevel = "L1")])

    # Create base deployer with memory platform
    deployer = mapDeployer(mem_platform,
                           graph,
                           inputTypes,
                           scheduler = _tilingScheduler,
                           deeployStateDir = _DEEPLOYSTATEDIR,
                           inputOffsets = inputOffsets)

    # Wrap with MemoryDeployerWrapper (adds memory level annotation)
    deployer = MemoryDeployerWrapper(deployer)

    # Wrap with TilerDeployerWrapper (adds tiling)
    deployer = TilerDeployerWrapper(deployer, workDir = _DEEPLOYSTATEDIR)

    # frontEnd() parses the graph; bind() triggers tiling via wrappers
    deployer.frontEnd()
    deployer.bind()
    deployer.prepared = True
    log.info("[XDNA2] Tiling completed, proceeding with MLIR generation")

    # Create output directory
    os.makedirs(args.dumpdir, exist_ok = True)

    # Write testinputs.h (raw BF16 bit patterns as uint16_t)
    testInputStr = _generate_xdna2_inputs_header(test_inputs_f32)
    with open(f'{args.dumpdir}/testinputs.h', 'w') as f:
        f.write(testInputStr)

    # Recompute golden outputs from the actual BF16 inputs the hardware will
    # see.  The original outputs.npz may have been computed in float32
    # precision, which can differ by several BF16 ULPs.
    bf16_inputs = [_float32_to_bf16_uint16(a.flatten()) for a in test_inputs_f32]
    bf16_input_f32 = [_bf16_to_float32(b) for b in bf16_inputs]
    golden_f32 = bf16_input_f32[0]
    for inp in bf16_input_f32[1:]:
        golden_f32 = golden_f32 + inp
    test_outputs_bf16 = [golden_f32.reshape(arr.shape) for arr in test_outputs_f32]

    # Write testoutputs.h (raw BF16 bit patterns as uint16_t)
    testOutputStr = _generate_xdna2_outputs_header(test_outputs_bf16)
    with open(f'{args.dumpdir}/testoutputs.h', 'w') as f:
        f.write(testOutputStr)

    # Write network.mlir
    mlir_str = deployer.generateMLIR()
    with open(f'{args.dumpdir}/network.mlir', 'w') as f:
        f.write(mlir_str)

    log.info(f"[XDNA2] Generated: testinputs.h, testoutputs.h, network.mlir -> {args.dumpdir}")


if __name__ == '__main__':
    parser = TestGeneratorArgumentParser(tiling_arguments = True,
                                         description = "Deeploy XDNA2 Code Generation Utility.")
    args, _ = parser.parse_known_args()

    if args.platform != 'XDNA2':
        parser.error(f"This script is for the XDNA2 platform. Got: {args.platform}")

    generateNetworkXDNA2(args)
