# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0
"""Test configuration for Generic platform."""

KERNEL_TESTS = [
    # FP32 Kernels
    "Kernels/FP32/ReLU",
    "Kernels/FP32/Softmax/Regular",
    "Kernels/FP32/Add/Regular",
    "Kernels/FP32/Conv/DW_2D_Bias",
    "Kernels/FP32/Conv/DW_2D_NoBias",
    "Kernels/FP32/Conv/DW_2D_ZeroValuedBias",
    "Kernels/FP32/Conv/Regular_2D_Bias",
    "Kernels/FP32/Conv/Regular_2D_NoBias",
    "Kernels/FP32/Conv/Regular_2D_ZeroValuedBias",
    "Kernels/FP32/Div",
    "Kernels/FP32/GEMM/Regular",
    "Kernels/FP32/MatMul",
    "Kernels/FP32/MaxPool",
    "Kernels/FP32/Mul",
    "Kernels/FP32/LayerNorm",
    "Kernels/FP32/RMSNorm/separate_ops",
    "Kernels/FP32/RMSNorm/single_fused_op",
    "Kernels/FP32/Pow/Scalar",
    "Kernels/FP32/Pow/Vector",
    "Kernels/FP32/ReduceMean/KeepDims/Add_ReduceMean",
    "Kernels/FP32/ReduceMean/KeepDims/Add_ReduceMean_Add",
    "Kernels/FP32/ReduceMean/KeepDims/AllAxes",
    "Kernels/FP32/ReduceMean/KeepDims/Axes1_2_3",
    "Kernels/FP32/ReduceMean/KeepDims/Axes1_3",
    "Kernels/FP32/ReduceMean/KeepDims/Axes2_1",
    "Kernels/FP32/ReduceMean/KeepDims/Axis0",
    "Kernels/FP32/ReduceMean/KeepDims/Axis2",
    "Kernels/FP32/ReduceMean/KeepDims/ReduceMean_Add",
    "Kernels/FP32/ReduceMean/NoKeepDims/Add_ReduceMean",
    "Kernels/FP32/ReduceMean/NoKeepDims/Add_ReduceMean_Add",
    "Kernels/FP32/ReduceMean/NoKeepDims/AllAxes",
    "Kernels/FP32/ReduceMean/NoKeepDims/Axes1_2_3",
    "Kernels/FP32/ReduceMean/NoKeepDims/Axes1_3",
    "Kernels/FP32/ReduceMean/NoKeepDims/Axes2_1",
    "Kernels/FP32/ReduceMean/NoKeepDims/Axis0",
    "Kernels/FP32/ReduceMean/NoKeepDims/Axis2",
    "Kernels/FP32/ReduceMean/NoKeepDims/ReduceMean_Add",
    "Kernels/FP32/Reshape/SkipConnection",
    "Kernels/FP32/Sqrt",
    "Kernels/FP32/Transpose",
    # Integer Kernels
    "Kernels/Integer/Softmax/Regular",
    "Kernels/Integer/Add/MultIO",
    "Kernels/Integer/Add/Regular",
    "Kernels/Integer/Conv/DW_1D",
    "Kernels/Integer/Conv/Regular_1D",
    "Kernels/Integer/Conv/DW_2D",
    "Kernels/Integer/Conv/Regular_2D",
    "Kernels/Integer/GEMM/Regular",
    "Kernels/Integer/MatMul/Add",
    "Kernels/Integer/MatMul/Regular",
    "Kernels/Integer/MaxPool",
    "Kernels/Integer/Pad/Regular_1D",
    "Kernels/Integer/Pad/Regular_2D",
    "Kernels/Integer/ReduceMean",
    "Kernels/Integer/ReduceSum",
    "Kernels/Integer/Slice",
    # Special test from TinyViT model layers
    "Models/TinyViT/5M/Layers/FP32/ReduceMean",
    # Mixed Precision / Quantization
    "Kernels/Mixed/Dequant",
    "Kernels/Mixed/Quant",
    "Models/Transformer_DeepQuant",
    "Kernels/Integer/Conv/DW_2D_RQ",
    "Kernels/Integer/Conv/Regular_2D_RQ",
    "Kernels/Integer/MatMul/Regular_RQ",
]

# Model tests - paths from generic-models job in workflow
MODEL_TESTS = [
    "Models/Autoencoder1D",
    "Models/CCT/FP32/CCT_1_16_16_8",
    "Models/CCT/FP32/CCT_2_32_32_128_Opset20",
    "Models/CCT/Int/ICCT",
    "Models/CCT/Int/ICCT_8",
    "Models/CCT/Int/ICCT_ITA",
    "Models/CCT/Int/ICCT_ITA_8",
    "Models/miniMobileNet",
    "Models/miniMobileNetv2",
    "Models/CNN_Linear1",
    "Models/TinyViT/Demo",
    "Models/WaveFormer",
    "Models/CNN_Linear2",
]
