# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI • Siracusa (Tiled)

"on":
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      docker_image_deeploy:
        description: "Deeploy Image to use"
        required: false
        default: "ghcr.io/pulp-platform/deeploy:devel"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  select-env:
    uses: ./.github/workflows/_select-env.yml
    with:
      docker_image_deeploy: ${{ inputs.docker_image_deeploy }}

  # Training tests - L2 singlebuffer
  siracusa-training-tiled-l2-singlebuffer:
    needs: select-env
    uses: ./.github/workflows/_runner-siracusa-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-marker: "training and l2 and singlebuffer"

  # Training tests - L3 singlebuffer (models that spill weights/activations to L3)
  siracusa-training-tiled-l3-singlebuffer:
    needs: select-env
    uses: ./.github/workflows/_runner-siracusa-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-marker: "training and l3 and singlebuffer"
